### PR TITLE
Gear and infantry units config

### PR DESCRIPTION
**Pull request by Donell0**
Gear and infantry units config from the latest BECTI Zerty preRelease4

### CODE REVIEW

**Comment by SpanishSurfer** [comment]
I can't merge this, you've changed upgrades, prices and way too much.  Sorry :(

**Comment by thecoolestname36** [comment]
Donnell0, I like the additions but you're going to have to normalize the prices before it gets merged.

**Comment by Donell0** [comment]
"you've changed upgrades, prices and way too much" that was exactly the plan)))) Ah, prices? Well, if you changed tje prices from original Zerty mission, then I will set mines accordingly. As for levels - the logic is following:
L0: 5,56 rifles, basic MG and basic marksmen rifles
L1: 6,5mm rifles, more advanced marksmen rifle to West, more advanced MG to East
L2: sniper rifles for West, MMG and more advanced marksmen rifle to East
L3: heavy sniper rifles, sniper rifles and MMG to West, sniper rifles to East

West: precision weapons focus
East: suppression weapons focus

**Comment by SpanishSurfer** [comment]
I appreciate the effort but the levels are fine as is. Lets focus on bug fixes for now.  We can discuss changing the levels at another time.

**Comment by Donell0** [comment]
well, I will commit only functionality-essential parts of the script and will keep prices scaling in mind) I will also check the gear menu GUI, it has to be changed too I believe. Thank you!

**Pull request closed without merging**
